web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: library/postgres:9.5
  ports:
    - "5432:5432"
  env_file:
    - '.env.db'
