web:
  build: .
  command: rails s -b 0.0.0.0 -e development
  volumes:
    - .:/var/app
  ports:
    - 3000:3000
  links:
    - db
    - rabbit

db:
  image: postgres
  env_file:
    - .env.db

rabbit:
  image: rabbitmq
